import assert from 'node:assert/strict';
import { outerContours, paintEraseStroke } from '../src/core/geometry/editing.mjs';
import { normalizeStickerBuilderManifest } from '../src/production/manifest.mjs';
import { buildStickerProductionPdf } from '../src/production/pdf.mjs';
const box = (x, y, size) => [[x,y],[x+size,y],[x+size,y+size],[x,y+size]];
const outer = box(0,0,.7), hole = box(.1,.1,.4), island = box(.2,.2,.1), separate = box(.8,.8,.1);
assert.deepEqual(outerContours([hole, separate, island, outer]), [separate, outer]);
assert.deepEqual(outerContours([outer.slice().reverse(),hole,separate]), [outer.slice().reverse(), separate]);
const concave = [[0,0],[.8,0],[.8,.2],[.2,.2],[.2,.8],[0,.8]];
assert.equal(outerContours([concave,box(.4,.4,.1)]).length,2,'open notch is not an enclosed hole');
const mask = new Uint8Array(100*100);
paintEraseStroke(mask,100,100,[10,50],[90,50],5);
for(let x=10;x<=90;x++) assert.equal(mask[50*100+x],1,'continuous stroke');
assert.equal(mask[10*100+50],0);
paintEraseStroke(mask,100,100,[50,50],[50,50],8,false);
assert.equal(mask[50*100+50],0); assert.equal(mask[50*100+10],1);
paintEraseStroke(mask,100,100,[-100,-100],[200,200],3);
assert.equal(mask[0],1); assert.equal(mask[9999],1);
const raw={width:2,height:2,quantity:50,renderWidth:1200,renderHeight:1200,perimeterInches:.1,contour:{paths:[outer,hole,separate],curveVersion:3}};
assert.equal(normalizeStickerBuilderManifest(raw).contour.paths.length,3,'legacy flag omitted preserves submitted geometry');
const manifest=normalizeStickerBuilderManifest({...raw,outerOutlineOnly:true,processing:{manualArtworkEdits:true,manualErasePixels:240,editRaster:{width:720,height:720}}});
assert.equal(manifest.contour.paths.length,2); assert.equal(manifest.outerOutlineOnly,true);
assert.equal(manifest.processing.manualErasePixels,240); assert.equal(manifest.processing.manualArtworkEdits,true);
const pdf = new TextDecoder().decode(buildStickerProductionPdf(new Uint8Array([255,216,255,217]),manifest));
assert.match(pdf,/0\.25 w/); assert.match(pdf,/\[\] 0 d/);
assert.equal(manifest.contour.commands.length,2,'same outer contours reach production PDF');
console.log('Outer contours, disconnected shapes, concave notches, brush interpolation/restoration and production metadata passed.');
